### ISSUE TITLE
question - Java

### ISSUE THREAD

**Issue by 452** [octave-de/serialize#1]
Hi, your serialization .m file work with binary type of serialization, like in Java serialization? For communicate between Java and GNU Octave(file, tcpip, streams), preferred in object style?

http://www.java-samples.com/showtutorial.php?tutorialid=398

**Comment by Andy1978** [comment]
No, it uses human readable instructions Luke JSON dies. If you want binary serialization use "typecast(class, "uint8")" from Octave

**Comment by Andy1978** [comment]
Ah... Android autocorrect... Like JSON does...

**Comment by 452** [comment]
thanks, I will try =)
